apiVersion: apps/v1
kind: Deployment
metadata:
  name: graduados-backend
  namespace: web-internacionales-appgraduados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graduados-backend
  template:
    metadata:
      labels:
        app: graduados-backend
    spec:
      imagePullSecrets:
      - name: harbor.unicen.edu.ar
      containers:
      - name: backend
        image: harbor.unicen.edu.ar/web/graduados-backend:1.0
        imagePullPolicy: Always    
        env:
        - name: DB_PATH
          valueFrom:
            configMapKeyRef:
              name: graduados-config
              key: DB_PATH
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: graduados-secrets
              key: JWT_SECRET
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: graduados-secrets
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: graduados-secrets
              key: SMTP_PASS
        volumeMounts:
        - name: database-storage
          mountPath: /app/data
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: graduados-db-pvc 