apiVersion: apps/v1
kind: Deployment
metadata:
  name: graduados-frontend
  namespace: web-internacionales-appgraduados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graduados-frontend
  template:
    metadata:
      labels:
        app: graduados-frontend
    spec:
      imagePullSecrets:
      - name: harbor.unicen.edu.ar
      containers:
      - name: frontend
        image: harbor.unicen.edu.ar/web/graduados-frontend:1.1
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "/graduados/api" 