apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graduados-ingress
  namespace: web-internacionales-mapa
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: "letsencrypt"
    #nginx.ingress.kubernetes.io/proxy- ody-size: 6224m
    nginx.ingress.kubernetes.io/proxy-body-size: 16224m
    #nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1200"
    #nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    #nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyAccess On
    #SecRule REQUEST_URI "@beginsWith /wp-admin" "id:1001,phase:1,pass,nolog,ctl:ruleRemoveById=949110"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - internacionalesgraduados.nuevo.unicen.edu.ar
    secretName: internacionalesgraduados.nuevo.unicen.edu.ar
  rules:
  - host: internacionalesgradudados.nuevo.unicen.edu.ar
    http:
      paths:
     # - path: /graduados (/|$)(.*)
      - path: /graduados 
        pathType: ImplementationSpecific
        backend:
          service:
            name: graduados-frontend
            port:
              number: 80
