apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graduados-ingress
  namespace: web-internacionales-mapa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: internacionalesmapa.nuevo.unicen.edu.ar
    http:
      paths:
      - path: /graduados(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: graduados-frontend
            port:
              number: 80
      - path: /graduados/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: graduados-backend
            port:
              number: 3000 