apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graduados-api
  namespace: web-internacionales-appgraduados
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyAccess On
      
      # Deshabilitar completamente ModSecurity para la API de graduados
      SecRule REQUEST_URI "@beginsWith /api/graduados" \
        "id:1001,phase:1,pass,nolog,ctl:ruleEngine=Off"
      
      # Deshabilitar ModSecurity para WebSocket
      SecRule REQUEST_URI "@beginsWith /socket.io/" \
        "id:1002,phase:1,pass,nolog,ctl:ruleEngine=Off"
      
      # Deshabilitar ModSecurity para uploads
      SecRule REQUEST_URI "@beginsWith /uploads" \
        "id:1004,phase:1,pass,nolog,ctl:ruleEngine=Off"
      
      # Alternativa: Deshabilitar reglas específicas si la anterior no funciona
      SecRule REQUEST_URI "@beginsWith /api/graduados" \
        "id:1003,phase:1,pass,nolog,ctl:ruleRemoveById=949110,ctl:ruleRemoveById=942200,ctl:ruleRemoveById=942100,ctl:ruleRemoveById=942110,ctl:ruleRemoveById=942120,ctl:ruleRemoveById=942130,ctl:ruleRemoveById=942140,ctl:ruleRemoveById=942150,ctl:ruleRemoveById=942160,ctl:ruleRemoveById=942170,ctl:ruleRemoveById=942180,ctl:ruleRemoveById=942190,ctl:ruleRemoveById=942200,ctl:ruleRemoveById=942210,ctl:ruleRemoveById=942220,ctl:ruleRemoveById=942230,ctl:ruleRemoveById=942240,ctl:ruleRemoveById=942250,ctl:ruleRemoveById=942260,ctl:ruleRemoveById=942270,ctl:ruleRemoveById=942280,ctl:ruleRemoveById=942290,ctl:ruleRemoveById=942300,ctl:ruleRemoveById=942310,ctl:ruleRemoveById=942320,ctl:ruleRemoveById=942330,ctl:ruleRemoveById=942340,ctl:ruleRemoveById=942350,ctl:ruleRemoveById=942360,ctl:ruleRemoveById=942370,ctl:ruleRemoveById=942380,ctl:ruleRemoveById=942390,ctl:ruleRemoveById=942400,ctl:ruleRemoveById=942410,ctl:ruleRemoveById=942420,ctl:ruleRemoveById=942430,ctl:ruleRemoveById=942440,ctl:ruleRemoveById=942450,ctl:ruleRemoveById=942460,ctl:ruleRemoveById=942470,ctl:ruleRemoveById=942480,ctl:ruleRemoveById=942490,ctl:ruleRemoveById=942500"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - internacionalesgraduados.unicen.edu.ar
    secretName: graduados-tls
  rules:
  - host: internacionalesgraduados.unicen.edu.ar
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: graduados-backend
            port:
              number: 3000
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: graduados-backend
            port:
              number: 3000
      - path: /uploads
        pathType: Prefix
        backend:
          service:
            name: graduados-backend
            port:
              number: 3000