apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graduados-db-pvc
  namespace: web-internacionales-mapa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-nvme-2-backup