apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graduados-uploads-pvc
  namespace: web-internacionales-appgraduados
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-nvme-2-backup 