apiVersion: apps/v1
kind: Deployment
metadata:
  name: graduados-backend
  namespace: web-internacionales-appgraduados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graduados-backend
  template:
    metadata:
      labels:
        app: graduados-backend
    spec:
      imagePullSecrets:
      - name: harbor.unicen.edu.ar
      containers:
      - name: backend
        image: harbor.unicen.edu.ar/web/graduados-backend:4.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DB_PATH
          valueFrom:
            configMapKeyRef:
              name: graduados-config
              key: DB_PATH
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: graduados-secrets
              key: JWT_SECRET
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: graduados-secrets
              key: SMTP_USER
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: graduados-secrets
              key: SMTP_PASS
        - name: FRONTEND_URL
          value: "https://internacionalesgraduados.unicen.edu.ar"
        - name: ADMIN_EMAIL
          valueFrom:
            configMapKeyRef:
              name: graduados-config
              key: ADMIN_EMAIL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: database-storage
          mountPath: /app/data
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: graduados-db-pvc 